[package]
name = "hive-server"
version = "0.1.0"
description = "The Hive game server."
authors = ["John Sirois <john.sirois@gmail.com>"]
publish = false

[dependencies]
clap = "2.32.0"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
