[package]
name = "hive-server"
version = "0.1.0"
description = "The Hive game server."
repository = "https://github.com/jsirois/hive"
authors = ["John Sirois <john.sirois@gmail.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
clap = "2.32.0"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
