[tasks.format-nightly]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "-v"]

[tasks.generate-favicon]
script_runner = "bash"
script = [
'''
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

cd "${ROOT}/app/static/images"
convert -scale 64x64 -background none icon.svg favicon.ico
'''
]

[tasks.app]
dependencies = [
  "generate-favicon"
]
script_runner = "bash"
script = [
'''
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

"${NVM_DIR}/nvm-exec" brunch build "${ROOT}/app"
'''
]

[tasks.bundle]
dependencies = [
  "app",
  "build-release"
]
script_runner = "bash"
script = [
'''
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

bundle="${ROOT}/dist/hive"
rm -rf "${bundle}" && mkdir -p "${bundle}"
ln -s "${ROOT}/app/public" "${bundle}/"
ln -s "${ROOT}/server/target/release/hive-server" "${bundle}/"

tar -Jhcf "${bundle}.tar.xz" -C "$(dirname "${bundle}")" "$(basename "${bundle}")"
'''
]
